import Link from "next/link";
import Image from "next/image";
import { BookHeart, CalendarDays, CheckCircle2, FileCheck2, GraduationCap, Leaf, Palette, ShieldCheck, Sparkles, Truck } from "lucide-react";
import { ProductCard } from "@/components/product-card";
import { StoreFooter } from "@/components/store-footer";
import { StoreHeader } from "@/components/store-header";
import { products } from "@/data/products";
const categories=[{name:"Datas comemorativas",icon:CalendarDays,color:"#ffe5ea"},{name:"Livros infantis",icon:BookHeart,color:"#fff0c9"},{name:"Atividades",icon:Palette,color:"#dff7e8"},{name:"Kits",icon:Sparkles,color:"#ece3ff"},{name:"Por ano escolar",icon:GraduationCap,color:"#dff2ff"},{name:"Disciplinas",icon:Leaf,color:"#ffe5ea"}];
export default function Home(){return <><StoreHeader/><main><section className="hero page-shell"><div className="hero-copy"><span className="hero-kicker">Materiais que encantam e ensinam</span><h1>Pequenos materiais,<br/><em>grandes aprendizagens!</em></h1><p>Livros, atividades e recursos pedagógicos prontos para tornar suas aulas mais criativas, inclusivas e significativas.</p><Link className="primary-button" href="#materiais">Ver materiais <span>→</span></Link></div><Image src="/images/hero-edupequenos.webp" alt="Duas crianças lendo juntas entre livros coloridos" width={1942} height={809} priority/></section><section className="benefits page-shell" aria-label="Benefícios"><div><Truck/><span><b>Entrega imediata</b><small>Receba após a confirmação</small></span></div><div><ShieldCheck/><span><b>Compra segura</b><small>Pagamento protegido</small></span></div><div><FileCheck2/><span><b>Material de qualidade</b><small>Pronto para imprimir</small></span></div><div><CheckCircle2/><span><b>Conteúdo alinhado</b><small>Pensado para educadores</small></span></div></section><section className="section page-shell"><div className="section-heading"><div><span>Encontre mais rápido</span><h2>Explore por categoria</h2></div><Link href="/?categoria=todas">Ver todas →</Link></div><div className="category-grid">{categories.map(({name,icon:Icon,color})=><Link href={`/?categoria=${encodeURIComponent(name)}`} key={name} style={{background:color}}><Icon/><b>{name}</b><span>→</span></Link>)}</div></section><section className="section page-shell" id="materiais"><div className="section-heading"><div><span>Escolhidos por educadores</span><h2>Materiais mais procurados</h2></div><Link href="/?categoria=todas">Ver todos →</Link></div><div className="products-grid">{products.filter(p=>p.featured).map(product=><ProductCard key={product.slug} product={product}/>)}</div></section><section className="newsletter page-shell"><div><span>✦</span><h2>Novidades que ajudam na sala de aula</h2><p>Receba lançamentos, materiais gratuitos e ideias para suas próximas aulas.</p></div><form><label className="sr-only" htmlFor="newsletter-email">Seu e-mail</label><input id="newsletter-email" type="email" placeholder="Seu melhor e-mail" required/><button>Quero receber</button></form></section></main><StoreFooter/></>}
